"""Initial migration

Revision ID: 3d3bb0cee6c3
Revises: 
Create Date: 2024-09-16 19:02:47.605350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3d3bb0cee6c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inboxes', 'url',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.drop_index('ix_inboxes_url', table_name='inboxes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_inboxes_url', 'inboxes', ['url'], unique=False)
    op.alter_column('inboxes', 'url',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
